#!/bin/bash

TO="your@email.com"
HOST="$(hostname -s)"
TYPE="${NOTIFYTYPE:-UNKNOWN}"
UPS="${UPSNAME:-unknown}"
MESSAGE="${1:-NUT notification}"

case "$TYPE" in
    ONBATT)
        SUBJECT="[$HOST] UPS ON BATTERY"
        ;;
    ONLINE)
        SUBJECT="[$HOST] UPS BACK ON LINE"
        ;;
    LOWBATT)
        SUBJECT="[$HOST] UPS LOW BATTERY"
        ;;
    FSD)
        SUBJECT="[$HOST] UPS FORCED SHUTDOWN"
        ;;
    SHUTDOWN)
        SUBJECT="[$HOST] HOST SHUTTING DOWN"
        ;;
    COMMOK)
        SUBJECT="[$HOST] UPS COMMUNICATION RESTORED"
        ;;
    COMMBAD)
        SUBJECT="[$HOST] UPS COMMUNICATION LOST"
        ;;
    NOCOMM)
        SUBJECT="[$HOST] UPS NOT AVAILABLE"
        ;;
    REPLBATT)
        SUBJECT="[$HOST] UPS BATTERY REPLACEMENT REQUIRED"
        ;;
    *)
        SUBJECT="[$HOST] NUT EVENT: $TYPE"
        ;;
esac

{
    printf 'From: %s\n' "proxmox@$HOST"
    printf 'To: %s\n' "$TO"
    printf 'Subject: %s\n' "$SUBJECT"
    printf '\n'
    printf 'UPS: %s\n' "$UPS"
    printf 'Event: %s\n' "$TYPE"
    printf 'Host: %s\n' "$HOST"
    printf '\n'
    printf '%s\n' "$MESSAGE"
} | /usr/bin/msmtp "$TO"
